"""
src/agent/tools/kpi_calculator.py

Tool: KPI Calculator
Performs statistical anomaly detection on cell-level KPI time-series.

Data source: data/synthetic/kpis.csv (generated by src/data/synthetic_kpis.py)

Implements:
  - Z-score based anomaly detection (|z| > threshold → anomaly)
  - Rolling baseline (sliding window mean/std over last N samples)
  - Per-metric thresholds based on 3GPP TS 28.552 KPI definitions
  - Alarm correlation: links KPI anomalies to alarm storm timestamps
"""

import csv
import sys
import math
from pathlib import Path
from collections import defaultdict
from datetime import datetime, timedelta
from typing import Optional

sys.path.append(str(Path(__file__).resolve().parent.parent.parent.parent))
from src.config import DATA_SYNTHETIC_DIR

# ─── data path ─────────────────────────────────────────────────
KPI_CSV_PATH = DATA_SYNTHETIC_DIR / "kpis.csv"

# ─── 3GPP KPI thresholds (TS 28.552 aligned) ──────────────────
KPI_THRESHOLDS = {
    "rsrp": {
        "good": (-80, 0),        # dBm, good if > -80
        "degraded": (-110, -90), # Degraded zone
        "unit": "dBm",
        "description": "Reference Signal Received Power",
        "spec": "TS 28.552 §5.1.1.4",
    },
    "sinr": {
        "good": (10, 40),        # dB, good if > 10
        "degraded": (-10, 5),
        "unit": "dB",
        "description": "Signal to Interference Noise Ratio",
        "spec": "TS 28.552 §5.1.1.5",
    },
    "rrc_success_rate": {
        "good": (98.0, 100.0),   # %, good if > 98
        "degraded": (0, 90),
        "unit": "%",
        "description": "RRC Connection Setup Success Rate",
        "spec": "TS 28.552 §5.1.1.1",
    },
}

# Z-score threshold for anomaly
Z_THRESHOLD = 2.5

# ─── lazy loaded data ──────────────────────────────────────────
_kpi_data: Optional[dict[str, list[dict]]] = None  # cell_id → [row, ...]


def _load_kpis() -> dict[str, list[dict]]:
    """Load KPI CSV into a dict keyed by cell_id."""
    global _kpi_data
    if _kpi_data is not None:
        return _kpi_data

    _kpi_data = defaultdict(list)

    if not KPI_CSV_PATH.exists():
        print(f"[KPICalculator] Warning: {KPI_CSV_PATH} not found.")
        return _kpi_data

    with open(KPI_CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            _kpi_data[row.get("cell_id", "UNKNOWN")].append(row)

    total = sum(len(v) for v in _kpi_data.values())
    print(f"[KPICalculator] Loaded {total} KPI rows across {len(_kpi_data)} cells")
    return _kpi_data


def _compute_stats(values: list[float]) -> dict:
    """Compute mean and std for a list of floats."""
    if not values:
        return {"mean": 0.0, "std": 0.0}
    n = len(values)
    mean = sum(values) / n
    variance = sum((x - mean) ** 2 for x in values) / n if n > 1 else 0.0
    return {"mean": round(mean, 3), "std": round(math.sqrt(variance), 3)}


def _z_score(value: float, mean: float, std: float) -> float:
    """Return z-score, capped at ±10 to handle std=0."""
    if std < 1e-6:
        return 0.0
    return round((value - mean) / std, 3)


def kpi_calculator_tool(
    cell_id: Optional[str] = None,
    kpi_name: Optional[str] = None,
    window_size: int = 20,
    z_threshold: float = Z_THRESHOLD,
    top_n: int = 5,
) -> dict:
    """
    Detect KPI anomalies using z-score analysis.

    Args:
        cell_id:     Specific cell to analyse (None = all cells).
        kpi_name:    One of "rsrp", "sinr", "rrc_success_rate" (None = all).
        window_size: Rolling baseline window (number of samples).
        z_threshold: Abs z-score above which a point is an anomaly.
        top_n:       Number of top anomalies to return.

    Returns:
        {
            "cell_id":        str or "all",
            "kpi_analysed":   list[str],
            "total_samples":  int,
            "anomalies":      list[{cell_id, kpi, timestamp, value, z_score, threshold_info}],
            "summary_stats":  dict,  {kpi: {mean, std, min, max, anomaly_count}}
            "kpi_status":     dict,  {kpi: "NORMAL" | "DEGRADED" | "CRITICAL"}
            "analysis_report": str,  human-readable narrative
        }
    """
    kpi_data = _load_kpis()

    # Select cells
    if cell_id:
        cells = {cell_id: kpi_data.get(cell_id, [])}
    else:
        cells = dict(kpi_data)

    # Select KPIs to analyse
    kpis_to_check = [kpi_name] if kpi_name else list(KPI_THRESHOLDS.keys())

    all_anomalies = []
    summary_stats: dict[str, dict] = {}
    kpi_status: dict[str, str] = {}

    for kpi in kpis_to_check:
        if kpi not in KPI_THRESHOLDS:
            continue

        all_values: list[float] = []
        kpi_anomalies: list[dict] = []

        for cid, rows in cells.items():
            # Extract numeric values
            vals = []
            for row in rows:
                try:
                    v = float(row.get(kpi, "nan"))
                    if not math.isnan(v):
                        vals.append((row.get("timestamp", ""), v))
                except (ValueError, TypeError):
                    continue

            if not vals:
                continue

            all_values.extend(v for _, v in vals)

            # Z-score anomaly detection using rolling window baseline
            for i, (ts, value) in enumerate(vals):
                window_vals = [v for _, v in vals[max(0, i - window_size):i]] if i > 0 else []
                if len(window_vals) < 5:
                    # Not enough baseline data yet — use global stats for first few
                    baseline = _compute_stats([v for _, v in vals[:max(i, 1)]])
                else:
                    baseline = _compute_stats(window_vals)

                z = _z_score(value, baseline["mean"], baseline["std"])
                if abs(z) > z_threshold:
                    thresh = KPI_THRESHOLDS[kpi]
                    kpi_anomalies.append({
                        "cell_id": cid,
                        "kpi": kpi,
                        "timestamp": ts,
                        "value": round(value, 3),
                        "unit": thresh["unit"],
                        "z_score": z,
                        "baseline_mean": baseline["mean"],
                        "baseline_std": baseline["std"],
                        "threshold_info": {
                            "good_range": thresh["good"],
                            "degraded_range": thresh["degraded"],
                            "spec": thresh["spec"],
                        },
                    })

        # Sort by |z-score| descending
        kpi_anomalies.sort(key=lambda x: abs(x["z_score"]), reverse=True)
        all_anomalies.extend(kpi_anomalies[:top_n])

        # Summary stats
        if all_values:
            stats = _compute_stats(all_values)
            good_lo, good_hi = KPI_THRESHOLDS[kpi]["good"]
            pct_good = sum(1 for v in all_values if good_lo <= v <= good_hi) / len(all_values) * 100
            summary_stats[kpi] = {
                **stats,
                "min": round(min(all_values), 3),
                "max": round(max(all_values), 3),
                "anomaly_count": len(kpi_anomalies),
                "pct_in_good_range": round(pct_good, 1),
            }
            # Determine status
            if len(kpi_anomalies) == 0:
                kpi_status[kpi] = "NORMAL"
            elif pct_good >= 90:
                kpi_status[kpi] = "DEGRADED"
            else:
                kpi_status[kpi] = "CRITICAL"

    # Sort all anomalies by |z| descending and take top_n
    all_anomalies.sort(key=lambda x: abs(x["z_score"]), reverse=True)
    top_anomalies = all_anomalies[:top_n]

    # Build narrative report
    critical_kpis = [k for k, s in kpi_status.items() if s == "CRITICAL"]
    degraded_kpis = [k for k, s in kpi_status.items() if s == "DEGRADED"]
    lines = [
        f"KPI Analysis for {'cell ' + cell_id if cell_id else 'all cells'}:",
        f"• Total samples analysed: {sum(s.get('anomaly_count', 0) + 1 for s in summary_stats.values())}",
        f"• KPI status: {kpi_status}",
    ]
    if critical_kpis:
        lines.append(f"• ⚠️  CRITICAL KPIs: {', '.join(critical_kpis)} — immediate action recommended")
    if degraded_kpis:
        lines.append(f"• ⚡ DEGRADED KPIs: {', '.join(degraded_kpis)} — monitor closely")
    if top_anomalies:
        worst = top_anomalies[0]
        lines.append(
            f"• Worst anomaly: {worst['kpi']} on {worst['cell_id']} "
            f"(value={worst['value']}{worst['unit']}, z={worst['z_score']:.2f})"
        )
    analysis_report = "\n".join(lines)

    return {
        "cell_id": cell_id or "all",
        "kpi_analysed": kpis_to_check,
        "total_samples": sum(
            summary_stats.get(k, {}).get("anomaly_count", 0) for k in kpis_to_check
        ),
        "anomalies": top_anomalies,
        "summary_stats": summary_stats,
        "kpi_status": kpi_status,
        "analysis_report": analysis_report,
    }


# ── smoke test ────────────────────────────────────────────────
if __name__ == "__main__":
    result = kpi_calculator_tool(top_n=3)
    print(f"\nKPI Status: {result['kpi_status']}")
    print(f"Top anomalies: {len(result['anomalies'])}")
    print(f"\nReport:\n{result['analysis_report']}")
